version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@2.0.0

workflows:
  main:
    jobs:
      - path-filtering/filter:
          mapping: |
            README.md readme-changed true
          config-path: .circleci/config.yml
      - hello-world:
          requires:
            - path-filtering/filter

parameters:
  readme-changed:
    type: boolean
    default: false

jobs:
  hello-world:
    docker:
      - image: cimg/base:stable
    steps:
      - unless:
          condition: << pipeline.parameters.readme-changed >>
          steps:
            - run:
                name: Hello World
                command: echo "Hello World!" 
      
      # - run:
      #     name: Hello World
      #     command: echo "Hello World!"
      #     unless: << pipeline.parameters.readme-changed >> # README.md以外のファイルが更新されたら実行
