version: 2.1

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  main:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/config.yml
          filters:
            ignore:
              - README.md
      - hello-world:
          requires:
            - path-filtering/filter

jobs:
  hello-world:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Hello World
          command: echo "Hello World!"
