version: 2.1

parameters:
  readme-changed:
    type: boolean
    default: false
  other-files-changed: # 新しいパラメータを追加
    type: boolean
    default: false

jobs:
  hello-world:
    docker:
      - image: cimg/base:stable
    steps:
      - unless: # README.md以外のファイルが更新されたら実行
          condition: << pipeline.parameters.readme-changed >>
          steps:
            - run:
                name: Hello World
                command: echo "Hello World!"

workflows:
  hello-workflow:
    when: << pipeline.parameters.other-files-changed >> # README.md以外の変更があった場合に実行
    jobs:
      - hello-world:
