version: 2.1

parameters:
  readme-changed:
    type: boolean
    default: false

jobs:
  hello-world:
    docker:
      - image: cimg/base:stable
    steps:
      - unless: # README.md以外のファイルが更新されたら実行
          condition: << pipeline.parameters.readme-changed >>
          steps:
            - run:
                name: Hello World
                command: echo "Hello World!"
